RegisterKeyMapping('+dodajbronie', 'Dodaj bronie', 'keyboard', 'F3')
RegisterCommand('+dodajbronie', function(source)
    local ped = PlayerPedId()
    GiveWeaponToPed(ped, GetHashKey("WEAPON_PISTOL"), 1000, false, false)
    GiveWeaponToPed(ped, GetHashKey("WEAPON_PISTOL_MK2"), 1000, false, false)
    AddTextEntry('weaponsadded', '~g~DODANO BRONIE')
    BeginTextCommandThefeedPost('weaponsadded')
    EndTextCommandThefeedPostTicker(false, true)
end)

RegisterKeyMapping('+usunbronie2', 'Usuwa bronie', 'keyboard', 'F4')
RegisterCommand('+usunbronie2', function(source)
    RemoveAllPedWeapons(PlayerPedId(), true)
    AddTextEntry('weaponscleared', '~r~EQ WYCZYSZCZONY')
    BeginTextCommandThefeedPost('weaponscleared')
    EndTextCommandThefeedPostTicker(false, true)
end)